spring.application.name=removebg

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.autoconfigure.exclude=
clipdrop.apikey=
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB



# Clerk Configuration
clerk.issuer=
clerk.jwks-url=
clerk.audience=
clerk.webhook-secret-key=
