spring.application.name=removebg

spring.datasource.url=jdbc:mysql://localhost:3306/removebgdb
spring.datasource.username=root
spring.datasource.password=root


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
clipdrop.apikey=ecb3e6bd2eb3ad873893d980fd3f5e2272a307e458fcffae775607f3a393ecf47e5b0a3e8cbb5e6c63555cbb01ac0363
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB



# Clerk Configuration
clerk.issuer=https://moral-ferret-28.clerk.accounts.dev
clerk.jwks-url=https://moral-ferret-28.clerk.accounts.dev/.well-known/jwks.json
clerk.audience=https://moral-ferret-28.clerk.accounts.dev
clerk.webhook-secret-key=whsec_wUf5hkYMq31AR8Tjm2PBvFh3KYZsmNDJ
jwt.secret=2bNmkBz+5spgQlMe2kF0KMxYUda4nkaYLyX/oTEnEQs=
